//import { Geist, Geist_Mono } from "next/font/google";
import MainHeader from "../../components/main-header";
import "./globals.css";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
*/

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div id="page">
        <h1>Next js routing and page rendering.</h1>
        <MainHeader />
        {children}
        </div>
      </body>
    </html>
  );
}
